cloud.aws.credentials.accessKey: foo
cloud.aws.credentials.secretKey: bar
cloud.aws.credentials.instanceProfile: false
cloud.aws.region.static: eu-central-1

sqs.queue: test-queue
sqs.queue.sns.fanout: test-queue-sns
sns.topic: test-topic

localstack:
  sns:
    url: http://localhost:4575
  sqs:
    url: http://localhost:4576
